stages:
  - build
  - deploy

compile:
  stage: build
  script: docker build -t ep2bot-template .
    
run:
  stage: deploy
  script:
    - echo -e "docker stop ep2bot-container\nexit 0" | bash
    - echo -e "docker rm ep2bot-container\nexit 0" | bash
    - >
      docker run -d --restart unless-stopped
      --env TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      --env TELEGRAM_ADMIN=$TELEGRAM_ADMIN
      --env GIT_URL=$GIT_URL
      --mount type=volume,source=ep2bot-volume,target=/app/data
      --name ep2bot-container ep2bot-template
  only: 
    - master